"""empty message

Revision ID: a49d5ed9146c
Revises: 632d6234dd4b
Create Date: 2026-08-11 21:07:48.633009

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a49d5ed9146c'
down_revision = '632d6234dd4b'
branch_labels = None
depends_on = None


def upgrade(engine_name):
    globals()["upgrade_%s" % engine_name]()


def downgrade(engine_name):
    globals()["downgrade_%s" % engine_name]()





def upgrade_():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade_():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def upgrade_server():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('room_chat', schema=None) as batch_op:
        batch_op.add_column(sa.Column('room_id', sa.Integer(), nullable=False))

    # ### end Alembic commands ###


def downgrade_server():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('room_chat', schema=None) as batch_op:
        batch_op.drop_column('room_id')

    # ### end Alembic commands ###

